export interface Quote {
  text: string
  author: string
}

const QUOTES: ReadonlyArray<Quote> = [
  { text: "You have power over your mind, not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "He who has a why to live for can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "Pain and suffering are always inevitable for a large intelligence and a deep heart.", author: "Fyodor Dostoevsky" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "Play long-term games with long-term people.", author: "Naval Ravikant" },
  { text: "The art of living is more like wrestling than dancing.", author: "Marcus Aurelius" },
  { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { text: "Knowing others is wisdom, knowing yourself is enlightenment.", author: "Lao Tzu" },
  { text: "The mystery of human existence lies not in just staying alive, but in finding something to live for.", author: "Fyodor Dostoevsky" },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
  { text: "Desire is a contract you make with yourself to be unhappy until you get what you want.", author: "Naval Ravikant" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
  { text: "You must have chaos within you to give birth to a dancing star.", author: "Friedrich Nietzsche" },
  { text: "When I let go of what I am, I become what I might be.", author: "Lao Tzu" },
  { text: "Above all, don't lie to yourself.", author: "Fyodor Dostoevsky" },
  { text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle" },
  { text: "Specific knowledge is knowledge you cannot be trained for.", author: "Naval Ravikant" },
  { text: "Be tolerant with others and strict with yourself.", author: "Marcus Aurelius" },
  { text: "He who fights with monsters should look to it that he himself does not become a monster.", author: "Friedrich Nietzsche" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "To live without hope is to cease to live.", author: "Fyodor Dostoevsky" },
  { text: "Patience is bitter, but its fruit is sweet.", author: "Aristotle" },
  { text: "Earn with your mind, not your time.", author: "Naval Ravikant" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "There is always some madness in love. But there is also always some reason in madness.", author: "Friedrich Nietzsche" },
  { text: "A good traveler has no fixed plans and is not intent on arriving.", author: "Lao Tzu" },
  { text: "Man only likes to count his troubles; he doesn't calculate his happiness.", author: "Fyodor Dostoevsky" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle" },
  { text: "A calm mind, a fit body, and a house full of love. These things cannot be bought.", author: "Naval Ravikant" },
  { text: "A man's true delight is to do the things he was made for.", author: "Marcus Aurelius" },
  { text: "The individual has always had to struggle to keep from being overwhelmed by the tribe.", author: "Friedrich Nietzsche" },
  { text: "Care about what other people think and you will always be their prisoner.", author: "Lao Tzu" },
  { text: "It is not the brains that matter most, but that which guides them.", author: "Fyodor Dostoevsky" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "The most important skill for getting rich is becoming a perpetual learner.", author: "Naval Ravikant" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius" },
  { text: "Become who you are.", author: "Friedrich Nietzsche" },
  { text: "Mastering others is strength. Mastering yourself is true power.", author: "Lao Tzu" },
  { text: "Happiness does not lie in happiness, but in the achievement of it.", author: "Fyodor Dostoevsky" },
  { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
  { text: "Free education is abundant, all over the Internet. It's the desire to learn that's scarce.", author: "Naval Ravikant" },
  { text: "If it is endurable, then endure it. Stop complaining.", author: "Marcus Aurelius" },
  { text: "To live is to suffer, to survive is to find some meaning in the suffering.", author: "Friedrich Nietzsche" },
  { text: "Silence is a source of great strength.", author: "Lao Tzu" },
  { text: "If you want to be respected by others, the great thing is to respect yourself.", author: "Fyodor Dostoevsky" },
  { text: "First, have a definite, clear practical ideal; a goal, an objective.", author: "Aristotle" },
  { text: "The big money is not in the buying and selling, but in the waiting.", author: "Charlie Munger" },
  { text: "If it is not right, do not do it; if it is not true, do not say it.", author: "Marcus Aurelius" },
  { text: "What is done out of love always takes place beyond good and evil.", author: "Friedrich Nietzsche" },
  { text: "Respond intelligently even to unintelligent treatment.", author: "Lao Tzu" },
  { text: "Everyone thinks of changing the world, but no one thinks of changing himself.", author: "Leo Tolstoy" },
  { text: "The first and greatest victory is to conquer yourself.", author: "Plato" },
  { text: "Spend each day trying to be a little wiser than you were when you woke up.", author: "Charlie Munger" },
  { text: "It is impossible for a man to learn what he thinks he already knows.", author: "Epictetus" },
  { text: "All truly great thoughts are conceived while walking.", author: "Friedrich Nietzsche" },
  { text: "If you do not change direction, you may end up where you are heading.", author: "Lao Tzu" },
  { text: "The two most powerful warriors are patience and time.", author: "Leo Tolstoy" },
  { text: "Wise men speak because they have something to say; fools because they have to say something.", author: "Plato" },
  { text: "Knowing what you don't know is more useful than being brilliant.", author: "Charlie Munger" },
  { text: "Confine yourself to the present.", author: "Marcus Aurelius" },
  { text: "The higher we soar the smaller we appear to those who cannot fly.", author: "Friedrich Nietzsche" },
  { text: "Great acts are made up of small deeds.", author: "Lao Tzu" },
  { text: "If you want to be happy, be.", author: "Leo Tolstoy" },
  { text: "The real tragedy of life is when men are afraid of the light.", author: "Plato" },
  { text: "The first rule of compounding: never interrupt it unnecessarily.", author: "Charlie Munger" },
  { text: "He who fears death will never do anything worthy of a living man.", author: "Seneca" },
  { text: "He who would learn to fly one day must first learn to stand and walk and run and climb and dance.", author: "Friedrich Nietzsche" },
  { text: "To attain knowledge, add things every day. To attain wisdom, remove things every day.", author: "Lao Tzu" },
  { text: "There is no greatness where there is no simplicity, goodness, and truth.", author: "Leo Tolstoy" },
  { text: "The measure of a man is what he does with power.", author: "Plato" },
  { text: "Take a simple idea and take it seriously.", author: "Charlie Munger" },
  { text: "Very little is needed to make a happy life.", author: "Marcus Aurelius" },
  { text: "The snake which cannot cast its skin has to die.", author: "Friedrich Nietzsche" },
  { text: "New beginnings are often disguised as painful endings.", author: "Lao Tzu" },
  { text: "Everything that I understand, I understand only because I love.", author: "Leo Tolstoy" },
  { text: "Be kind, for everyone you meet is fighting a hard battle.", author: "Plato" },
  { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { text: "True happiness is to enjoy the present, without anxious dependence upon the future.", author: "Seneca" },
  { text: "Invisible threads are the strongest ties.", author: "Friedrich Nietzsche" },
  { text: "At the center of your being you have the answer; you know who you are and you know what you want.", author: "Lao Tzu" },
  { text: "Joy can only be real if people look upon their life as a service.", author: "Leo Tolstoy" },
  { text: "Courage is knowing what not to fear.", author: "Plato" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { text: "The best revenge is not to be like your enemy.", author: "Marcus Aurelius" },
  { text: "Sometimes people don't want to hear the truth because they don't want their illusions destroyed.", author: "Friedrich Nietzsche" },
  { text: "The supreme art of war is to subdue the enemy without fighting.", author: "Sun Tzu" },
  { text: "He who has felt the deepest grief is best able to experience supreme happiness.", author: "Leo Tolstoy" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "Most powerful is he who has himself in his own power.", author: "Seneca" },
  { text: "One repays a teacher badly if one always remains nothing but a pupil.", author: "Friedrich Nietzsche" },
  { text: "Know yourself and know your enemy, and you will never be defeated.", author: "Sun Tzu" },
  { text: "We know what we are, but know not what we may be.", author: "William Shakespeare" },
  { text: "I know that I know nothing.", author: "Socrates" },
  { text: "The important thing is not to stop questioning.", author: "Albert Einstein" },
  { text: "When you arise in the morning, think of what a precious privilege it is to be alive.", author: "Marcus Aurelius" },
  { text: "No price is too high to pay for the privilege of owning yourself.", author: "Friedrich Nietzsche" },
  { text: "In the midst of chaos, there is also opportunity.", author: "Sun Tzu" },
  { text: "To thine own self be true.", author: "William Shakespeare" },
  { text: "The secret of change is to focus all of your energy not on fighting the old, but on building the new.", author: "Socrates" },
  { text: "Once we accept our limits, we go beyond them.", author: "Albert Einstein" },
  { text: "Associate with people who are likely to improve you.", author: "Seneca" },
  { text: "Convictions are more dangerous foes of truth than lies.", author: "Friedrich Nietzsche" },
  { text: "The greatest victory is that which requires no battle.", author: "Sun Tzu" },
  { text: "The fool doth think he is wise, but the wise man knows himself to be a fool.", author: "William Shakespeare" },
  { text: "He is richest who is content with the least.", author: "Socrates" },
  { text: "Life is like riding a bicycle. To keep your balance you must keep moving.", author: "Albert Einstein" },
  { text: "Look within. Within is the fountain of good, and it will ever bubble up if you will ever dig.", author: "Marcus Aurelius" },
  { text: "There are no facts, only interpretations.", author: "Friedrich Nietzsche" },
  { text: "Appear weak when you are strong, and strong when you are weak.", author: "Sun Tzu" },
  { text: "It is not in the stars to hold our destiny but in ourselves.", author: "William Shakespeare" },
  { text: "Wonder is the beginning of wisdom.", author: "Socrates" },
  { text: "The way to get startup ideas is not to try to think of startup ideas.", author: "Paul Graham" },
  { text: "No person has the power to have all they want, but it is in their power not to want what they don't have.", author: "Seneca" },
  { text: "The man who does not wish to belong to the mass needs only to cease taking himself easily.", author: "Friedrich Nietzsche" },
  { text: "When you are content to be simply yourself and don't compare or compete, everybody will respect you.", author: "Lao Tzu" },
  { text: "Cowards die many times before their deaths; the valiant never taste of death but once.", author: "William Shakespeare" },
  { text: "Be as you wish to seem.", author: "Socrates" },
  { text: "Live in the future, then build what's missing.", author: "Paul Graham" },
  { text: "Death smiles at us all; all a man can do is smile back.", author: "Marcus Aurelius" },
  { text: "And those who were seen dancing were thought to be insane by those who could not hear the music.", author: "Friedrich Nietzsche" },
  { text: "Opportunities multiply as they are seized.", author: "Sun Tzu" },
  { text: "There is nothing either good or bad, but thinking makes it so.", author: "William Shakespeare" },
  { text: "No man ever steps in the same river twice, for it's not the same river and he's not the same man.", author: "Heraclitus" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "Our life is what our thoughts make it.", author: "Marcus Aurelius" },
  { text: "Nobody realizes that some people expend tremendous energy merely to be normal.", author: "Albert Camus" },
  { text: "Anticipate the difficult by managing the easy.", author: "Lao Tzu" },
  { text: "Our doubts are traitors, and make us lose the good we oft might win by fearing to attempt.", author: "William Shakespeare" },
  { text: "The only constant in life is change.", author: "Heraclitus" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "Accept the things to which fate binds you, and love the people with whom fate brings you together.", author: "Marcus Aurelius" },
  { text: "We should consider every day lost on which we have not danced at least once.", author: "Friedrich Nietzsche" },
  { text: "He will win who knows when to fight and when not to fight.", author: "Sun Tzu" },
  { text: "How poor are they that have not patience! What wound did ever heal but by degrees?", author: "William Shakespeare" },
  { text: "Character is destiny.", author: "Heraclitus" },
  { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { text: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius" },
  { text: "Life is not a problem to be solved, but a reality to be experienced.", author: "Soren Kierkegaard" },
  { text: "The superior man is satisfied and composed; the mean man is always full of distress.", author: "Confucius" },
  { text: "Action is eloquence.", author: "William Shakespeare" },
  { text: "Day by day, what you choose, what you think and what you do is who you become.", author: "Heraclitus" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "How much trouble he avoids who does not look to see what his neighbor says or does.", author: "Marcus Aurelius" },
  { text: "The advantage of a bad memory is that one enjoys several times the same good things for the first time.", author: "Friedrich Nietzsche" },
  { text: "Victorious warriors win first and then go to war.", author: "Sun Tzu" },
  { text: "Even the darkest night will end and the sun will rise.", author: "Victor Hugo" },
  { text: "Much learning does not teach understanding.", author: "Heraclitus" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius" },
  { text: "Faith is the highest passion in a human being.", author: "Soren Kierkegaard" },
  { text: "By three methods we may learn wisdom: by reflection, by imitation, and by experience.", author: "Confucius" },
  { text: "Life is the flower for which love is the honey.", author: "Victor Hugo" },
  { text: "Talent hits a target no one else can hit; genius hits a target no one else can see.", author: "Arthur Schopenhauer" },
  { text: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill" },
  { text: "Reject your sense of injury and the injury itself disappears.", author: "Marcus Aurelius" },
  { text: "No one can build you the bridge on which you must cross the river of life, no one but you alone.", author: "Friedrich Nietzsche" },
  { text: "Let your plans be dark and impenetrable as night, and when you move, fall like a thunderbolt.", author: "Sun Tzu" },
  { text: "He who opens a school door, closes a prison.", author: "Victor Hugo" },
  { text: "A man can do what he wants, but not want what he wants.", author: "Arthur Schopenhauer" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "Loss is nothing else but change, and change is Nature's delight.", author: "Marcus Aurelius" },
  { text: "The doer alone learns.", author: "Friedrich Nietzsche" },
  { text: "Before you embark on a journey of revenge, dig two graves.", author: "Confucius" },
  { text: "Taking a new step, uttering a new word, is what people fear most.", author: "Fyodor Dostoevsky" },
  { text: "Every man takes the limits of his own field of vision for the limits of the world.", author: "Arthur Schopenhauer" },
  { text: "Read what you love until you love to read.", author: "Naval Ravikant" },
  { text: "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it.", author: "Marcus Aurelius" },
  { text: "In the midst of winter, I found there was, within me, an invincible summer.", author: "Albert Camus" },
  { text: "Build your opponent a golden bridge to retreat across.", author: "Sun Tzu" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "The two enemies of human happiness are pain and boredom.", author: "Arthur Schopenhauer" },
  { text: "All I want to know is where I'm going to die, so I'll never go there.", author: "Charlie Munger" },
  { text: "Do every act of your life as if it were your last.", author: "Marcus Aurelius" },
  { text: "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.", author: "Albert Camus" },
  { text: "The whole secret of existence is to have no fear.", author: "Buddha" },
  { text: "Boredom is the desire for desires.", author: "Leo Tolstoy" },
  { text: "Compassion is the basis of morality.", author: "Arthur Schopenhauer" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { text: "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.", author: "Marcus Aurelius" },
  { text: "One must imagine Sisyphus happy.", author: "Albert Camus" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
  { text: "My life has been full of terrible misfortunes most of which never happened.", author: "Michel de Montaigne" },
  { text: "Keep your identity small.", author: "Paul Graham" },
  { text: "Concentrate every minute on doing what is in front of you with precise and genuine seriousness.", author: "Marcus Aurelius" },
  { text: "Real generosity toward the future lies in giving all to the present.", author: "Albert Camus" },
  { text: "Raise your words, not your voice. It is rain that grows flowers, not thunder.", author: "Rumi" },
  { text: "Give every man thy ear, but few thy voice.", author: "William Shakespeare" },
  { text: "The greatest thing in the world is to know how to belong to oneself.", author: "Michel de Montaigne" },
  { text: "It is not what happens to you, but how you react to it that matters.", author: "Epictetus" },
  { text: "What is happiness except the simple harmony between a man and the life he leads?", author: "Albert Camus" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
  { text: "He who fears he will suffer, already suffers because he fears.", author: "Michel de Montaigne" },
  { text: "We have two ears and one mouth so that we can listen twice as much as we speak.", author: "Epictetus" },
  { text: "Life can only be understood backwards; but it must be lived forwards.", author: "Soren Kierkegaard" },
  { text: "The best time to plant a tree was twenty years ago. The second best time is now.", author: "Chinese proverb" },
  { text: "To love another person is to see the face of God.", author: "Victor Hugo" },
  { text: "When we are no longer able to change a situation, we are challenged to change ourselves.", author: "Viktor Frankl" },
  { text: "No man is free who is not master of himself.", author: "Epictetus" },
  { text: "Anxiety is the dizziness of freedom.", author: "Soren Kierkegaard" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "Experience is simply the name we give our mistakes.", author: "Oscar Wilde" },
  { text: "Hope is a waking dream.", author: "Aristotle" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus" },
  { text: "To dare is to lose one's footing momentarily. Not to dare is to lose oneself.", author: "Soren Kierkegaard" },
  { text: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius" },
  { text: "Don't let schooling interfere with your education.", author: "Mark Twain" },
  { text: "The last of the human freedoms is to choose one's attitude in any given set of circumstances.", author: "Viktor Frankl" },
  { text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus" },
  { text: "Once you label me you negate me.", author: "Soren Kierkegaard" },
  { text: "He who learns but does not think is lost. He who thinks but does not learn is in great danger.", author: "Confucius" },
  { text: "I can resist everything except temptation.", author: "Oscar Wilde" },
  { text: "What is to give light must endure burning.", author: "Viktor Frankl" },
  { text: "Don't explain your philosophy. Embody it.", author: "Epictetus" },
  { text: "Patience is necessary, and one cannot reap immediately where one has sown.", author: "Soren Kierkegaard" },
  { text: "Wheresoever you go, go with all your heart.", author: "Confucius" },
  { text: "Always forgive your enemies; nothing annoys them so much.", author: "Oscar Wilde" },
  { text: "Let him that would move the world first move himself.", author: "Socrates" },
  { text: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus" },
  { text: "We are our choices.", author: "Jean-Paul Sartre" },
  { text: "When anger rises, think of the consequences.", author: "Confucius" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "In some way, suffering ceases to be suffering at the moment it finds a meaning.", author: "Viktor Frankl" },
  { text: "Circumstances don't make the man, they only reveal him to himself.", author: "Epictetus" },
  { text: "Man is condemned to be free.", author: "Jean-Paul Sartre" },
  { text: "The superior man is modest in his speech but exceeds in his actions.", author: "Confucius" },
  { text: "A man who does not think for himself does not think at all.", author: "Oscar Wilde" },
  { text: "One ought, every day, to hear a little song, read a good poem, and see a fine picture.", author: "Johann Wolfgang von Goethe" },
  { text: "Don't seek to have events happen as you wish, but wish them to happen as they do.", author: "Epictetus" },
  { text: "Freedom is what you do with what's been done to you.", author: "Jean-Paul Sartre" },
  { text: "To see what is right and not to do it is want of courage.", author: "Confucius" },
  { text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
  { text: "Lost time is never found again.", author: "Benjamin Franklin" },
  { text: "If you want to improve, be content to be thought foolish and stupid.", author: "Epictetus" },
  { text: "What is great in man is that he is a bridge and not an end.", author: "Friedrich Nietzsche" },
  { text: "Study the past if you would define the future.", author: "Confucius" },
  { text: "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did.", author: "Mark Twain" },
  { text: "A wise man will make more opportunities than he finds.", author: "Francis Bacon" },
  { text: "Any person capable of angering you becomes your master.", author: "Epictetus" },
  { text: "The secret for harvesting from existence the greatest fruitfulness and enjoyment is to live dangerously.", author: "Friedrich Nietzsche" },
  { text: "Flow with whatever may happen, and let your mind be free.", author: "Zhuangzi" },
  { text: "Courage is resistance to fear, mastery of fear, not absence of fear.", author: "Mark Twain" },
  { text: "Reading maketh a full man; conference a ready man; and writing an exact man.", author: "Francis Bacon" },
  { text: "Men are disturbed not by things, but by the views which they take of things.", author: "Epictetus" },
  { text: "It is my ambition to say in ten sentences what others say in a whole book.", author: "Friedrich Nietzsche" },
  { text: "Happiness is the absence of striving for happiness.", author: "Zhuangzi" },
  { text: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", author: "Mark Twain" },
  { text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "Johann Wolfgang von Goethe" },
  { text: "No great thing is created suddenly.", author: "Epictetus" },
  { text: "Every deep thinker is more afraid of being understood than of being misunderstood.", author: "Friedrich Nietzsche" },
  { text: "The wise man looks into space and does not regard the small as too little, nor the great as too big.", author: "Zhuangzi" },
  { text: "Kindness is the language which the deaf can hear and the blind can see.", author: "Mark Twain" },
  { text: "Whatever you can do or dream you can, begin it. Boldness has genius, power and magic in it.", author: "Johann Wolfgang von Goethe" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "We love life, not because we are used to living but because we are used to loving.", author: "Friedrich Nietzsche" },
  { text: "No one saves us but ourselves. We ourselves must walk the path.", author: "Buddha" },
  { text: "Continuous improvement is better than delayed perfection.", author: "Mark Twain" },
  { text: "He who moves not forward, goes backward.", author: "Johann Wolfgang von Goethe" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
  { text: "I am not upset that you lied to me; I am upset that from now on I cannot believe you.", author: "Friedrich Nietzsche" },
  { text: "Holding on to anger is like grasping a hot coal with the intent of throwing it; you are the one who gets burned.", author: "Buddha" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "A man sees in the world what he carries in his heart.", author: "Johann Wolfgang von Goethe" },
  { text: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca" },
  { text: "The higher the type of man, the more rarely he succeeds.", author: "Friedrich Nietzsche" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
  { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
  { text: "Treat people as if they were what they ought to be and you help them become what they are capable of being.", author: "Johann Wolfgang von Goethe" },
  { text: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca" },
  { text: "The visionary lies to himself, the liar only to others.", author: "Friedrich Nietzsche" },
  { text: "What you seek is seeking you.", author: "Rumi" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "Every new beginning comes from some other beginning's end.", author: "Seneca" },
  { text: "There are no eternal facts, as there are no absolute truths.", author: "Friedrich Nietzsche" },
  { text: "The wound is the place where the light enters you.", author: "Rumi" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "By failing to prepare, you are preparing to fail.", author: "Benjamin Franklin" },
  { text: "As long as you live, keep learning how to live.", author: "Seneca" },
  { text: "The most spiritual human beings experience by far the most painful tragedies.", author: "Friedrich Nietzsche" },
  { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi" },
  { text: "Always do what you are afraid to do.", author: "Ralph Waldo Emerson" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "Sometimes even to live is an act of courage.", author: "Seneca" },
  { text: "You will never be happy if you continue to search for what happiness consists of.", author: "Albert Camus" },
  { text: "Set your life on fire. Seek those who fan your flames.", author: "Rumi" },
  { text: "Nothing great was ever achieved without enthusiasm.", author: "Ralph Waldo Emerson" },
  { text: "Either write something worth reading or do something worth writing.", author: "Benjamin Franklin" },
  { text: "While we wait for life, life passes.", author: "Seneca" },
  { text: "There is no love of life without despair of life.", author: "Albert Camus" },
  { text: "Stop acting so small. You are the universe in ecstatic motion.", author: "Rumi" },
  { text: "The only way to have a friend is to be one.", author: "Ralph Waldo Emerson" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "A gem cannot be polished without friction, nor a man perfected without trials.", author: "Seneca" },
  { text: "The absurd is born of the confrontation between the human need and the unreasonable silence of the world.", author: "Albert Camus" },
  { text: "Be like a tree and let the dead leaves drop.", author: "Rumi" },
  { text: "Finish each day and be done with it. You have done what you could.", author: "Ralph Waldo Emerson" },
  { text: "People of accomplishment rarely sat back and let things happen. They went out and happened to things.", author: "Leonardo da Vinci" },
  { text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca" },
  { text: "At any street corner the feeling of absurdity can strike any man in the face.", author: "Albert Camus" },
  { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
  { text: "Time stays long enough for anyone who will use it.", author: "Leonardo da Vinci" },
  { text: "No man was ever wise by chance.", author: "Seneca" },
  { text: "A man's work is nothing but this slow trek to rediscover those two or three great and simple images in whose presence his heart first opened.", author: "Albert Camus" },
  { text: "I went to the woods because I wished to live deliberately.", author: "Henry David Thoreau" },
  { text: "All of humanity's problems stem from man's inability to sit quietly in a room alone.", author: "Blaise Pascal" },
  { text: "If a man knows not to which port he sails, no wind is favorable.", author: "Seneca" },
  { text: "Our life is frittered away by detail. Simplify, simplify.", author: "Henry David Thoreau" },
  { text: "The heart has its reasons which reason knows nothing of.", author: "Blaise Pascal" },
  { text: "Throw me to the wolves and I will return leading the pack.", author: "Seneca" },
  { text: "It's not what you look at that matters, it's what you see.", author: "Henry David Thoreau" },
  { text: "Man is but a reed, the most feeble thing in nature; but he is a thinking reed.", author: "Blaise Pascal" },
  { text: "The whole future lies in uncertainty: live immediately.", author: "Seneca" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "Every man is guilty of all the good he did not do.", author: "Voltaire" },
  { text: "Wherever there is a human being, there is an opportunity for a kindness.", author: "Seneca" },
  { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Henry David Thoreau" },
  { text: "Judge a man by his questions rather than his answers.", author: "Voltaire" },
  { text: "Man grows used to everything, the scoundrel!", author: "Fyodor Dostoevsky" },
  { text: "Think for yourself and let others enjoy the privilege of doing so too.", author: "Voltaire" },
  { text: "I say let the world go to hell, but I should always have my tea.", author: "Fyodor Dostoevsky" },
  { text: "The good life is one inspired by love and guided by knowledge.", author: "Bertrand Russell" },
  { text: "The cleverest of all is the man who calls himself a fool at least once a month.", author: "Fyodor Dostoevsky" },
  { text: "The whole problem with the world is that fools and fanatics are always so certain of themselves, and wiser people so full of doubts.", author: "Bertrand Russell" },
  { text: "A man who lies to himself and believes his own lies becomes unable to recognize truth in himself or in anyone else.", author: "Fyodor Dostoevsky" },
  { text: "To fear love is to fear life, and those who fear life are already three parts dead.", author: "Bertrand Russell" },
  { text: "Much unhappiness has come into the world because of bewilderment and things left unsaid.", author: "Fyodor Dostoevsky" },
  { text: "Until you make the unconscious conscious, it will direct your life and you will call it fate.", author: "Carl Jung" },
  { text: "Power is given only to him who dares to lower himself and pick it up.", author: "Fyodor Dostoevsky" },
  { text: "The most terrifying thing is to accept oneself completely.", author: "Carl Jung" },
  { text: "If you want to overcome the whole world, overcome yourself.", author: "Fyodor Dostoevsky" },
  { text: "Knowing your own darkness is the best method for dealing with the darknesses of other people.", author: "Carl Jung" },
  { text: "It is the great mystery of human life that old grief passes gradually into quiet tender joy.", author: "Fyodor Dostoevsky" },
  { text: "Who looks outside, dreams; who looks inside, awakes.", author: "Carl Jung" },
  { text: "Nothing in this world is harder than speaking the truth, nothing easier than flattery.", author: "Fyodor Dostoevsky" },
  { text: "Every man carries the whole of humanity's condition within him.", author: "Michel de Montaigne" },
  { text: "Nothing is easier than to denounce the evildoer; nothing is more difficult than to understand him.", author: "Fyodor Dostoevsky" },
  { text: "I quote others only to better express myself.", author: "Michel de Montaigne" },
  { text: "The privilege of a lifetime is being who you are.", author: "Joseph Campbell" },
  { text: "The most certain sign of wisdom is a continual cheerfulness.", author: "Michel de Montaigne" },
  { text: "Follow your bliss and the universe will open doors where there were only walls.", author: "Joseph Campbell" },
  { text: "Wealth is like sea-water; the more we drink, the thirstier we become.", author: "Arthur Schopenhauer" },
  { text: "We must be willing to let go of the life we planned so as to have the life that is waiting for us.", author: "Joseph Campbell" },
  { text: "Boredom is the feeling that everything is a waste of time; serenity, that nothing is.", author: "Arthur Schopenhauer" },
  { text: "The deeper that sorrow carves into your being, the more joy you can contain.", author: "Kahlil Gibran" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "Out of suffering have emerged the strongest souls; the most massive characters are seared with scars.", author: "Kahlil Gibran" },
  { text: "The greatest weapon against stress is our ability to choose one thought over another.", author: "William James" },
  { text: "You talk when you cease to be at peace with your thoughts.", author: "Kahlil Gibran" },
  { text: "Begin to be now what you will be hereafter.", author: "William James" },
  { text: "No bird soars too high if he soars with his own wings.", author: "William Blake" },
  { text: "The sad truth is that most evil is done by people who never make up their minds to be good or evil.", author: "Hannah Arendt" },
  { text: "The road of excess leads to the palace of wisdom.", author: "William Blake" },
  { text: "Storytelling reveals meaning without committing the error of defining it.", author: "Hannah Arendt" },
  { text: "He who has done his best for his own time has lived for all times.", author: "Friedrich Schiller" },
  { text: "Act only according to that maxim by which you can, at the same time, will that it should become a universal law.", author: "Immanuel Kant" },
  { text: "Keep true to the dreams of thy youth.", author: "Friedrich Schiller" },
  { text: "Two things fill the mind with ever-increasing wonder: the starry heavens above me and the moral law within me.", author: "Immanuel Kant" },
  { text: "A person may cause evil to others not only by his actions but by his inaction.", author: "John Stuart Mill" },
  { text: "The only freedom which deserves the name is that of pursuing our own good in our own way.", author: "John Stuart Mill" },
  { text: "A wise man proportions his belief to the evidence.", author: "David Hume" },
  { text: "Beauty in things exists in the mind which contemplates them.", author: "David Hume" },
  { text: "Change your life today. Don't gamble on the future, act now, without delay.", author: "Simone de Beauvoir" },
]

/** Day of the year, 1–366. */
export function dayOfYear(d: Date): number {
  const start = Date.UTC(d.getFullYear(), 0, 0)
  const current = Date.UTC(d.getFullYear(), d.getMonth(), d.getDate())
  return Math.floor((current - start) / 86_400_000)
}

export function getQuoteForDate(d: Date = new Date()): Quote {
  const index = (dayOfYear(d) - 1) % QUOTES.length
  return QUOTES[index]
}
